# Dockerfile.base

# Define the ARG before the FROM instruction (this is required)
ARG provider_image=docker.io/library/alpine:3.19

# Use the ARG in the FROM instruction
FROM ${provider_image} AS qsc-httpd-provider_redhat

# ONBUILD instructions that will be triggered in child images
ONBUILD ARG qsc_deployment_dir
ONBUILD ARG HTTPD_UID
ONBUILD ARG HTTPD_USER

ONBUILD RUN echo "qsc_deployment_dir=$qsc_deployment_dir, HTTPD_UID=$HTTPD_UID, HTTPD_USER=$HTTPD_USER" > /onbuild-args.txt
